version: '3'
services:
  dev:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
    - 3001:3000
    volumes:
    - /apps/node_modules
    - .:/apps
  prod:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
    - 3000:80